security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Parc\UserBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_COLLAB:	  [ROLE_USER]
        ROLE_ADMIN:       [ROLE_COLLAB, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        principal:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        connexion:
            pattern: ^/login$
            anonymous: true
            
        principal:
            pattern: ^/
            anonymous: false
            provider: principal
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
            remember_me:
                key: %secret%

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
