parameters:
#    parc_user.example.class: Parc\UserBundle\Example

services:
#    parc_user.example:
#        class: %parc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
