<?php

namespace Parc\PuffinsBagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BagueurBGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BagueurBGRepository extends EntityRepository
{
	public function getListBagueurs($responsable, $role)
	{
		$query = $this->createQueryBuilder('bg');
		if($role != 'ROLE_SUPER_ADMIN'){
			if($responsable != '' && $responsable != null){
				$query->where('bg.responsable = :responsable')
					->setParameter('responsable', $responsable);
			}else{
				$query->where('bg.responsable = :responsable')
					->setParameter('responsable', 0);
			}
		}
		$query->orderBy('bg.nom', 'ASC');				
		return $query;
	}
	
	public function getBagueur($nomCRBPO)
	{
		$query = $this->createQueryBuilder('bg')
					 ->where('bg.nomCRBPO = :nomCRBPO')					 
					 ->setParameter('nomCRBPO', $nomCRBPO);
				
		return $query->getQuery()
					->getOneOrNullResult();
	}
}
