<?php

namespace Parc\PuffinsBagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColonieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonieRepository extends EntityRepository
{
}
