<?php

namespace Parc\PuffinsBagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonneesPNPCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesPNPCRepository extends EntityRepository
{
}
