<?php

namespace Parc\PuffinsBagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonneesCRBPORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesLocalisationRepository extends EntityRepository
{
	public function getLocalisation($lieudit)
	{
		$query = $this->createQueryBuilder('loc')
				->where('lower(loc.lieudit) = lower(:lieudit)')
				->setParameter('lieudit', $lieudit);
				
		return $query->getQuery()
					->getOneOrNullResult();
	}
}
